### ISSUE TITLE
add Hebrew WG citation

### ISSUE THREAD

**Issue by vmarchman** [langcog/wordbank#206] opened 2021-04-19 16:21 UTC
Please update the contributors page to replace the current citation for this citation for Hebrew WG:

GENDLER-SHALEV, H., & DROMI, E. (2021). The Hebrew Web Communicative Development Inventory (MB-CDI): Lexical Development Growth Curves. Journal of Child Language, 1-17.

**Comment by alv1nn** [comment] 2021-09-08 18:02
duplicate of #223

**Closed by alv1nn** 2021-09-08 18:02 UTC
